version: '3'

services:
  pq-toolkit-ui-dev:
    build:
      context: ../pq-toolkit-ui
      dockerfile: Dockerfile
      args:
        ENV: dev
        DATA_PATH: "/pq-toolkit/data"
    image: pq-toolkit-ui-dev
    ports:
      - 80:3000
    volumes:
      - pq-toolkit-data:/pq-toolkit/data

volumes:
  pq-toolkit-data:
