version: '3'

services:
  pq-toolkit-ui-stage:
    build:
      context: ../pq-toolkit-ui
      dockerfile: Dockerfile
      args:
        ENV: stage
        DATA_PATH: "/pq-toolkit/data"
    image: pq-toolkit-ui-stage
    ports:
      - 80:3000
    volumes:
      - pq-toolkit-data:/pq-toolkit/data

volumes:
  pq-toolkit-data:
